### ISSUE TITLE
New Release Breaks Oomox PKGBUILD

### ISSUE THREAD

**Issue by gardotd426** [themix-project/themix-plugin-base16#1]
As of the new release, not only is the PKGBUILD for oomox broken because of an incorrect md5sum, it's actually just flat-out broken due to incorrect directory names. Here's the relevant PKGBUILD lines:

```
_base16_cmt=2ddee2a03653850ed2166e7766636bf1dfb21ca5
"base16_mirror-${_base16_cmt}.tar.gz::https://github.com/themix-project/base16_mirror/archive/${_base16_cmt}.tar.gz"
cp -pr "base16_mirror-${_base16_cmt}"/* "${pkgname}-${_oomox_ver}/plugins/base16/base16_mirror"
```
Wrong md5sum aside (the correct one is 67be13f352485c70970a1a18bedb9b21, the one in the PKGBUILD is incorrect), as you can see, `makepkg` is expecting there to be a directory called `base16_mirror-2ddee2a03653850ed2166e7766636bf1dfb21ca5/`. But when the tar.gz archive is extracted, the directory is actually called `themix-plugin-base-16-2ddee2a03653850ed2166e7766636bf1dfb21ca5/`. I don't know when this was changed, but it completely breaks oomox from building.

**Comment by gardotd426** [comment]
Here's a PKGBUILD that at least builds correctly (whether or not it'll actually work, I'm not sure, although I imagine it would):
[PKGBUILD.zip](https://github.com/themix-project/themix-plugin-base16/files/4371378/PKGBUILD.zip)

**Comment by actionless** [comment]
thanks! merged
