### ISSUE TITLE
Error loading plugin "base16"

### ISSUE THREAD

**Issue by ohhskar** [themix-project/themix-plugin-base16#3]
I'm getting an error whenever I startup themix with the plugin. 

![image](https://user-images.githubusercontent.com/15758219/136034176-5144d63e-ea84-46cd-b7df-49804611da9e.png)

I can't seem to copy from the window, so I'm posting a screenshot of the error and traceback instead.

I'm on the master branch of themix-gui, with themix-icons-papirus and themix-theme-materia installed.

**Comment by actionless** [comment]
oh, prolly it's time to release the new themix-gui :D  (https://github.com/themix-project/oomox/pull/403)

**Comment by actionless** [comment]
thanks for reporting!
