### ISSUE TITLE
oomox-tomorrow-night(inverse): Audacity's menu bar shortcut key display is too dark to see

### ISSUE THREAD

**Issue by tkna91** [themix-project/themix-plugin-base16#4]
The shortcut keys (in this case "Space") in Audacity's submenu displays (e.g. "Transport->Playing->Play/Stop Space") are too dark to see.
The non "Inverse GUI Variant" is visible.

https://user-images.githubusercontent.com/102382754/204089508-2e31a2c0-1aac-4d59-8a54-4247c3eb09cc.mp4

```
$ pacman -Qsq themix | xargs pacman -Q
themix-export-spotify-git 1.2.6.r1.gf47c36b-1
themix-full-git 1.15-2
themix-gui-git 1.15.r28.ga78cc920-1
themix-icons-archdroid-git 1.0.3.r0.gb90779de4-1
themix-icons-gnome-colors-git 5.5.6.r0.gd2cb7eb-2
themix-icons-numix-git 22.11.17.r1.g97e19b3d5.e6197dd14-1
themix-icons-papirus-git 20221101.r10.g6fe16ea79b-1
themix-icons-suru-plus-aspromauros-git 3.0.r0.gd43a8ec4-2
themix-icons-suru-plus-git 30.0.r2.g9bd895f32-2
themix-import-images-git 1.15.r28.ga78cc920-1
themix-plugin-base16-git 1.5.1.r8.g77f0bfa-1
themix-theme-oomox-git 1.12.3.r1.ge87724dd-1
$ pacman -Q audacity sway-im-git wlroots-git linux
audacity 1:3.2.1-2
sway-im-git r7015.94b69acf-1
wlroots-git 0.17.0.r5941.c02872e0-1
linux 6.0.9.arch1-1
$ 
```

**Comment by actionless** [comment]
1) base16 plugin is only converting between Themix and Base16 templates

2) your screenshot is broken

3) audacity is funny, it's drawing half of widgets HARDCODED, half from gtk (2?) theme - just forget about it ;)

**Comment by tkna91** [comment]
I have uploaded the screencast to another site.
https://streamable.com/ex6r22

I see, understand.
Thanks for your kind response.

**Comment by actionless** [comment]
i checked your video, and also double-checked that audacity is using gtk3,

so the correct way to verify gtk3 theme is via gtk3-widget-factory and gtk3-demos apps:

![2022-11-26-183312_1920x1080_scrot](https://user-images.githubusercontent.com/1655669/204101597-edb6d23d-c01c-45d1-a0fc-4713996f5797.png)

**Comment by actionless** [comment]
you could also check your theme with gtk3-widget-factory app and in case if it's ok in widget factory but not in audacity - you can report the bug there

**Comment by actionless** [comment]
in real life situation, most probably, the only thing you could do - is creating a custom shortcut/alias for your audacity to run it with a different, than system, theme:

```
GTK_THEME=my-theme-name-light audacity
```

**Comment by tkna91** [comment]
Thanks. That idea looks quite realistic.
Maybe I can use adwaita-dark with `sed` or something to replace the color values to match my theme.

**Comment by tkna91** [comment]
The gtk3-widget-factory test pattern does not seem to have a submenu shortcut key display. I am a little surprised that the menu shortcut key display and the submenu shortcut key display are two different things.

https://streamable.com/vxq4wy

**Comment by actionless** [comment]
>  I am a little surprised that the menu shortcut key display and the submenu shortcut key display are two different things.

i've checked that theory - it's indeed true, you can see in Nemo first-level hotkeys are rendered in gray but second-level items in black:
![2022-11-26-193135_1920x1080_scrot](https://user-images.githubusercontent.com/1655669/204103916-fc0ce798-5515-4e7d-8f15-abe46a8a2a82.png)
