### ISSUE TITLE
Exporting Theme as Application configs with Base16 Export Plugin

### ISSUE THREAD

**Issue by ethanmoss1** [themix-project/themix-plugin-base16#5]
# Issue
Ive come across an issue trying to export themes using the Base16 theme exporter.
When trying to export, there is no textbox with the output of the config and when exporting you get a blank file.

Installing from ARCH using the Themix_full_git package. All configuration files from ~.config/oomox have been wiped for testing.

# Temporary Fixes
It starts with the below error;
```
Traceback (most recent call last):
  File "/opt/oomox/plugins/base16/oomox_plugin.py", line 297, in _on_app_changed
    if self._variants_changed_signal:
AttributeError: 'Base16ExportDialog' object has no attribute '_variants_changed_signal'
```
Now I was able to fix this by initialising the int `_variants_changed_signal` to 0, which I believe then allows the code to pass this if statement and populates varaints the drop down
```
215    _variants_changed_signal: int = 0  # temp fix
```
This leads onto a second error.
```
Traceback (most recent call last):
  File "/opt/oomox/plugins/base16/oomox_plugin.py", line 338, in _on_variant_changed
    self.base16_stuff()
  File "/opt/oomox/plugins/base16/oomox_plugin.py", line 256, in base16_stuff
    base16_theme = convert_oomox_to_base16(
  File "/opt/oomox/plugins/base16/oomox_plugin.py", line 120, in convert_oomox_to_base16
    raise RuntimeError(theme_error)
RuntimeError: BASE16_GENERATE_DARK of theme is not 'string'.
```
This seems to stem from a check in converting of oomox theme to base 16 theme. it seems the dictionary values are populated with strings, bools and ints but the code checks only for strings. I temporarily fixed this by disabling the instance check and its works for now. (not a permanent fix IMO)
```
117     for key, value in colorscheme.items():
118         # if not isinstance(value, str):
119             # theme_error = f"{key} of theme is not 'string'."
120             # raise RuntimeError(theme_error)
121         base16_theme[f'themix_{key}'] = value
```

That leads to two final errors, both of which seem to go hand in hand.

When loading the base16 export options it doesn't create a config until you export, this returns an error about getting the default path. This seems to solve itself after exporting once and it creating a config, allowing the code to get the 'default path'.
```
Traceback (most recent call last):
  File "/opt/oomox/plugins/base16/oomox_plugin.py", line 338, in _on_variant_changed
    self.base16_stuff()
  File "/opt/oomox/plugins/base16/oomox_plugin.py", line 271, in base16_stuff
    self.export_config[self.OPTIONS.DEFAULT_PATH]
  File "/opt/oomox/oomox_gui/settings.py", line 74, in __getitem__
    return self.config[item]
KeyError: 'default_path'
```
```
173 class ConfigKeys:
174     default_path = 'default_path'
175     last_app = 'last_app'
176     last_variant = 'last_variant'
...
363         self.export_config = ExportConfig(
364             config_name='base16',
365             default_config={
366                 ConfigKeys.default_path: self.OPTIONS.DEFAULT_PATH,
367                 ConfigKeys.last_variant: None,
368                 ConfigKeys.last_app: None,
369            },
370         )
```
The issue is you cant export until you have the multiline textbox with the output rendered. This is stopped due to what seems is the `rendered_them` variable, temp fix was to initalise like the first issue.
```
Traceback (most recent call last):
  File "/opt/oomox/oomox_gui/export_common.py", line 126, in <lambda>
    self.apply_button.connect("clicked", lambda x: self.do_export())
  File "/opt/oomox/plugins/base16/oomox_plugin.py", line 251, in do_export
    fobj.write(self.rendered_theme)
AttributeError: 'Base16ExportDialog' object has no attribute 'rendered_theme'
```
```
213    rendered_theme: str = ""
```

**Comment by actionless** [comment]
what are the versions of gui and base16 plugin?

nvm, i found that code by names

**Comment by actionless** [comment]
Thanks for reporting!
You can check with `-git` AUR package if it works for you now.

**Comment by ethanmoss1** [comment]
Ah yes sorry, glad I was of help to you.

Tested it on my machine and works as intended, Thanks!

**Comment by actionless** [comment]
thanks for the very detailed report - it indeed made the fix faster 😺👍
