### ISSUE TITLE
 different headerbar color when window is active/unactive 

### ISSUE THREAD

**Issue by demostanis** [themix-project/themix-plugin-base16#6]
moved from https://github.com/themix-project/themix-gui/issues/487...
is there an option/would it be possible to have an option to indicate a different color for the headerbar when its window is active and unactive?
i tried to change WM_BORDER_{UN,}FOCUS but that did not have any effect.

**Comment by actionless** [comment]
it's again wrong repo 😺

base16 plugin itself doesn't have any themes except for these 6 (https://github.com/themix-project/themix-plugin-base16/tree/master/templates_extra), it's only list of other repos:

https://github.com/themix-project/themix-plugin-base16/blob/master/templates.yaml

**Comment by actionless** [comment]
links to all other, non-base16 plugins are in the About screen, btw:

![2023-09-08--1694197089_3840x2160_scrot](https://github.com/themix-project/themix-plugin-base16/assets/1655669/25c920fc-ada7-4884-b546-0e147adc0bed)
